### ISSUE TITLE
make a readme

### ISSUE THREAD

**Issue by geoknee** [geoknee/gdap#1]
At present, this is just a bag of matlab functions!

**Comment by jebej** [comment]
Hello George,
I am trying to reimplement the algorithm from the paper, and would love a README and a license for this project, so that I may know if I'm allowed to look at it.
Thanks,
Jeremy

**Comment by geoknee** [comment]
Hi Jeremy

Sure thing. I’m travelling at the moment but will try and get on this ASAP.

George

**Comment by geoknee** [comment]
@jebej, I tried to clean things up as best I could. Take a look and let me know if anything is still unclear!
